{% set name = "vispy" %}
{% set version = "0.16.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b93c32c85d08c06ae8f5e3177f9cfd6c495e1745f2120b777830adee5d9c3648
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - wheel
    - setuptools >=69.4.0
    - numpy {{ numpy }}
    - setuptools_scm >=8.1
    - cython >=3.0.0
  run:
    - python
    - numpy
    - freetype-py
    - hsluv
    - kiwisolver
    - packaging
  run_constrained:
    - pyglet >=1.2

# E   ModuleNotFoundError: No module named 'meshio'
{% set deselect_tests = " --deselect=io/tests/test_io.py::test_meshio" %}
# >   return (px.width/mm.width + px.height/mm.height) * 0.5 * 25.4
#             ^^^^^^^^^^^^^^^^^
# E   ZeroDivisionError: division by zero
{% set deselect_tests = deselect_tests + " --deselect=app/tests/test_backends.py::test_template" %}  # [osx]
{% set deselect_tests = deselect_tests + " --deselect=util/dpi/tests/test_dpi.py::test_dpi" %}  # [osx]
test:
  imports:
    - vispy
    - vispy.util.dpi
    - vispy.util.fonts
  commands:
    - pip check
    - pytest --pyargs vispy {{ deselect_tests }}
  requires:
   - pip
   - pytest
   - pillow

about:
  home: https://vispy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: High performance interactive 2D/3D data visualization.
  description: |
    VisPy is a Python library for interactive scientific visualization that is
    designed to be fast, scalable, and easy to use.
  doc_url: https://vispy.org/overview.html
  dev_url: https://github.com/vispy/vispy

extra:
  recipe-maintainers:
    - davidh-ssec
    - kmuehlbauer
  skip-lints:
    - missing_doc_source_url
    - missing_license_url