{% set version = "0.7.3" %}

package:
  name: vispy
  version: {{ version }}

source:
  fn: vispy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vispy/vispy-{{ version }}.tar.gz
  sha256: 1edd3434247577e0910f9c76331b82a54be7e5381c022120c7336e73167b155c
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - numpy
    - fontconfig  # [unix]
    - cython

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]
    - freetype-py
    - hsluv
    - kiwisolver

test:
  imports:
    - vispy
    # make sure that platform-specific dpi functions can be imported
    - vispy.util.dpi
    - vispy.util.fonts
    # todo: check headless testing
  #requires:
  #  - pyqt 4.*
  #commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: High performance interactive 2D/3D data visualization.
  description: |
    VisPy is a Python library for interactive scientific visualization that is
    designed to be fast, scalable, and easy to use.
  doc_url: http://vispy.org/documentation.html
  dev_url: https://github.com/vispy/vispy

extra:
  recipe-maintainers:
    - davidh-ssec
    - kmuehlbauer
