{% set name = "vispy" %}
{% set version = "0.14.3" %}

package:
  name: vispy
  version: {{ version }}

source:
  fn: vispy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: efbbb847a908baf7e7169ab9bf296138a39364f367e6cb0a8ec03ad71699d31d
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - setuptools >=42
    - setuptools_scm >=7.1
    - numpy >=2
    - fontconfig  # [unix]
    - cython >=3.0.0
    - packaging
    - wheel

  run:
    - python
    - numpy
    - fontconfig  # [unix]
    - freetype-py
    - hsluv
    - kiwisolver
    - packaging

test:
  imports:
    - vispy
    # make sure that platform-specific dpi functions can be imported
    - vispy.util.dpi
    - vispy.util.fonts
  requires:
   - pip
  # Only needed for the local UI testing. 
  #  - pyqt
  #  - pytest
  commands:
    - pip check
    # Run the test suite, but requires a display. This is not possible in CI.
    # - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: https://vispy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: High performance interactive 2D/3D data visualization.
  description: |
    VisPy is a Python library for interactive scientific visualization that is
    designed to be fast, scalable, and easy to use.
  doc_url: https://vispy.org/overview.html
  dev_url: https://github.com/vispy/vispy

extra:
  recipe-maintainers:
    - davidh-ssec
    - kmuehlbauer
  skip-lints:
    - missing_doc_source_url
    - missing_license_url