{% set version = "0.6.6" %}

package:
  name: vispy
  version: {{ version }}

source:
  fn: vispy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vispy/vispy-{{ version }}.tar.gz
  sha256: 6f3c4d00be9e6761c046d520a86693d78a0925d47eeb2fc095e95dac776f74ee
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy
    - fontconfig  # [unix]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    # Will be taken care of by run_exports
    # - fontconfig  # [unix]

test:
  imports:
    - vispy
  # todo: check headless testing
  #requires:
  #  - pyqt 4.*
  #commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: High performance interactive 2D/3D data visualization.
  description: |
    VisPy is a Python library for interactive scientific visualization that is
    designed to be fast, scalable, and easy to use.
  doc_url: http://vispy.org/documentation.html
  dev_url: https://github.com/vispy/vispy

extra:
  recipe-maintainers:
    - davidh-ssec
    - kmuehlbauer
