# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Y98ajTO1KI3IQaz7wLbfnbfRC9bjRwnOSc3FfyuoDB6cjSJATiBYoIoT5OpibYGGT8FMDM+4DtZ2tUPqA6uMdjgF/MWQXw6OoNh0pKKd2xAubVaxgy4umSa6w0Yz18rXdRg0GKccruxnaoUyYQ4mBSD0KJ9GHM5ZOr9CHT60m18J023KtqAd4achowFuW5MD5wc16cTYBM/ODa1+72A7ZczsHlxaMo2KgRZyMqP/lRNRZqd18xBfIECYS9vsBbfvSD4LVaFFB1Pem1fWQeaWehtpQZrIjq03G/LNDUl1cHhvuEXVEAWtKLw6uTp8bJmeZStKO5id1yEzmZ4qjINJne2F/qp8WgAraX90XI15dqeAZ14VOFxEiZE4NtC4Vpzhct8BKcfve8jLbbztrreT2E8UxOUyteKBiZWYeig11aMs1O85ExHjqo/g5fql8LFUv4/4VxLgo+2t9XSMRwHXtFyQ98Hq7y21CXTrw5BPStm+TKxnHlL8otiA3jJjR2k355V4+K4z9CSs7oPRB505q90Ib9GaTcOqmjZhiQ6WJAJtEW5jXD/AXFSXJoPl+I2hCfJsDxnTAFx+baQW24SAvpwxdepVR9T0xon0gG2sRBTxkbpBee4OwNh3td6aXwKLIXcUCaxUo6cMgUbPRR8bEPz+Epgxvtsi9sYDsPZ+dCM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
