travis:
  secure:
    BINSTAR_TOKEN: Y98ajTO1KI3IQaz7wLbfnbfRC9bjRwnOSc3FfyuoDB6cjSJATiBYoIoT5OpibYGGT8FMDM+4DtZ2tUPqA6uMdjgF/MWQXw6OoNh0pKKd2xAubVaxgy4umSa6w0Yz18rXdRg0GKccruxnaoUyYQ4mBSD0KJ9GHM5ZOr9CHT60m18J023KtqAd4achowFuW5MD5wc16cTYBM/ODa1+72A7ZczsHlxaMo2KgRZyMqP/lRNRZqd18xBfIECYS9vsBbfvSD4LVaFFB1Pem1fWQeaWehtpQZrIjq03G/LNDUl1cHhvuEXVEAWtKLw6uTp8bJmeZStKO5id1yEzmZ4qjINJne2F/qp8WgAraX90XI15dqeAZ14VOFxEiZE4NtC4Vpzhct8BKcfve8jLbbztrreT2E8UxOUyteKBiZWYeig11aMs1O85ExHjqo/g5fql8LFUv4/4VxLgo+2t9XSMRwHXtFyQ98Hq7y21CXTrw5BPStm+TKxnHlL8otiA3jJjR2k355V4+K4z9CSs7oPRB505q90Ib9GaTcOqmjZhiQ6WJAJtEW5jXD/AXFSXJoPl+I2hCfJsDxnTAFx+baQW24SAvpwxdepVR9T0xon0gG2sRBTxkbpBee4OwNh3td6aXwKLIXcUCaxUo6cMgUbPRR8bEPz+Epgxvtsi9sYDsPZ+dCM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
